name: "Continuous Integration"

on:
  pull_request:
  push:
    branches-ignore: ["pr/**"]
    tags: ["**"]
  workflow_dispatch:

defaults:
  run:
    shell: "bash"

jobs:
  ci-linux:
    name: Linux CI
    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@v1
    with:
      cabuild_ref: "v1"
      linux: true
      m32: true
      matrixmode: true
      valgrind: true

  ci-linux-ptrace:
    name: Linux CI with PTrace
    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@v1
    with:
      cabuild_ref: "v1"
      linux: true
      mesonargs: '-Dptrace=true'

  ci-macos:
    name: MacOS CI
    uses: bus1/cabuild/.github/workflows/ci-c-util.yml@v1
    with:
      cabuild_ref: "v1"
      linux: false
      macos: true

  ci-docs:
    name: Documentation CI
    uses: bus1/cabuild/.github/workflows/ci-sphinx.yml@v1
    with:
      meson: true
      source: "./src/docs"
